### ISSUE TITLE
allow arguments to be passed in any order

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/dependents-cli#3]
Currently args are expected to be repo name then flags. IMHO it shouldn't matter what order they are in, in particular if you want to check a few packages and you're using flags, it's easier to enter the name as the last argument so you can just repeat the previous command and change the name

**Comment by doowb** [comment]
You mean like doing something like?:

``` sh
dependents --format --downloads micomatch
```

Any ideas on how to enable that with `yargs-parser`?

I could probably do it manaully by checking to see if `downloads` is a string and `repo` isn't set and set it, but `--format` is allowed to be a string so doing `dependents --downloads --format micomatch` would require checking if `--format` is a string and one of the available formats.

I can also setup aliases for `-f` and `-d` for the flags.

Until it's updated, this will work:

``` sh
dependents --format --downloads --repo micomatch
```

**Comment by doowb** [comment]
Done! Install the latest to see the updates.

This was a lot easier than I expected. I just had to set options on `yargs-parser` so that it would see the `--downloads` flag as a boolean and set some defaults for `--format`
